### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BannerBomb** [PoomSmart/EmojiLibrary#10]
Hey, what are the differences between these 3?
![image](https://user-images.githubusercontent.com/11788894/69832150-cd2d0f80-11fa-11ea-9548-50ccd9d5f0fa.png)

**Comment by PoomSmart** [comment]
1. For iOS 12+
2. For any iOS versions
3. IIRC emoji fonts from iOS 8.3 or 9 era, end users don't need them in most cases
