### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by rctfan929** [PoomSmart/EmojiLibrary#12]
I can’t get iOS 14 emojis to render correctly. I’ve tried both emjoifont manager and the manual method. Which font should I use?

iPhone 6s iOS 13.5

**Comment by PoomSmart** [comment]
Visit this page and download the font. The links are up-to-date. http://poomsmart.github.io/repo/emoji10.html

**Comment by rctfan929** [comment]
Using that font and the manual method messes up all my emojis. Using EFM the new emoji don’t render.

**Comment by JuliOooO36** [comment]
I get blank icons(ios13.5/u0) 
![3B3D03FE-40D1-485C-B2CA-993C3C599C6A](https://user-images.githubusercontent.com/16007391/94790423-e2834500-039b-11eb-9c59-a0a301ecc4fa.jpeg)

**Comment by PoomSmart** [comment]
https://twitter.com/PoomSmart/status/1311959704688418816
