### ISSUE TITLE
[Bug] Keyboard and Notification Center crashing

### ISSUE THREAD

**Issue by yllshahini** [PoomSmart/EmojiLibrary#14]
Recently updated EmojiPort to 1.0.9 and EmojiPort Resources to 1.2 but everytime I try open the emoji keyboard or a notification that contains an emoji it crashes.

Running iOS 12.0.1 on iPhone X with uncover 5.3.1

**Comment by PoomSmart** [comment]
Crash log will be appreciated.

**Comment by yllshahini** [comment]
Sure thing, I have a couple more crashes if you need them. [Drive Folder](https://drive.google.com/drive/folders/1-wvJA9lupnXDXNRWdsTHXk1DB6R1fpzI?usp=sharing)

**Comment by PoomSmart** [comment]
@yllshahini Could you ensure every EmojiPort tweak is the latest one and is from my repo?

**Comment by yllshahini** [comment]
Just updated EmojiPort and EmojiAttributes to beta versions. EP=1.0.10~b1, EA=1.4.1~b1 Uploaded another crash log to the drive folder after updating.

**Comment by PoomSmart** [comment]
@yllshahini Could you update EmojiPort (iOS 12.0 - 14.1) tweak to version 1.0.10~b3 ?

**Comment by yllshahini** [comment]
Updated and seems to be working fine now both in apps and Notification Center. Thanks for the support. ☺️

**Comment by PoomSmart** [comment]
Thanks for testing.
