### ISSUE TITLE
some new emojis do not display correctly

### ISSUE THREAD

**Issue by r0my** [PoomSmart/EmojiLibrary#19]
Hello!

I have a problem with display the 14.5 emojis correctly. I'm using poomsmarts tweak a lot of years, but this time, i can not get them working. 

I'm on 13.6 and have installed the new font AppleColorEmoji@2x (74,8mb) to the right folder (...Library/Fonts/Core).
Installed are also

Attributes 1.4.4 b4
Fontmanager 0.0.8.4
Library 12.2 b5
Port (12-14.4) 1.1 b5
PortResources 1.2.3

I reload the Font, test to change it, restart iphone with no luck. 

![FDA75967-D403-4623-843C-B6C80CAE37A0](https://user-images.githubusercontent.com/12330184/111100203-7a8a7a80-8547-11eb-99f9-e94fdc3e6787.jpeg)

**Comment by PoomSmart** [comment]
Show me the font you placed inside `/System/Library/Fonts/Core`.

**Comment by r0my** [comment]
![E73FBBFE-6C60-401D-AAE4-B6CE3FFB27BE](https://user-images.githubusercontent.com/12330184/111112113-e842a080-855f-11eb-8c40-8f00ab611a39.jpeg)

Downloaded from https://github.com/PoomSmart/EmojiLibrary/releases/tag/0.14.5 - 

Assets / AppleColorEmoji@2x.ttc
71.3 MB

![Uploading 411F771A-7E49-4DFE-8D29-82DC0A6113DE.jpeg…]()

**Comment by PoomSmart** [comment]
Then why do you need EmojiFontManager?

**Comment by r0my** [comment]
> Then why do you need EmojiFontManager?

Should i delete it?
