### ISSUE TITLE
Blank emoji keyboard on iOS 10+ (but works fine on iOS 11.3.1)

### ISSUE THREAD

**Issue by yur1xpp** [PoomSmart/EmojiLibrary#2]
Many users [reported ](https://www.reddit.com/r/jailbreak/comments/9luyi1/discussion_i_think_poomsmart_updated_the_emoji/e79nqr8/)that the emoji keyboard is blank after manually changing the emoji fonts on iOS. Would you have a look?

Thank you :)

**Comment by JMccormick264** [comment]
I am having the same issue on iOS 10.1.1 as well

**Comment by StrangeOne101** [comment]
Try replace `AppleColorEmoji@2x.cff` as well as `AppleColorEmoji@2x.ttc` with the provided `AppleColorEmoji@2x.ttc` file. On iOS 10.2 and that worked for me.
