### ISSUE TITLE
AppleColorEmoji@2x.ttf is not a valid font in windows.

### ISSUE THREAD

**Issue by KunalTanwar** [PoomSmart/EmojiLibrary#20]
I downloaded `Apple Color Emoji@2x.ttf` but whenever I am opening it showing me this error :
![image](https://user-images.githubusercontent.com/77537933/128642239-b4181b01-d189-4af1-bc8f-73d4feb0cf38.png)

**MY OS DETAILS**
EDITION - Windows 10 Home Single Language
VERSION - 21H1
OS BUILD - 19043.1110

**Comment by PoomSmart** [comment]
The font is not for reading from Windows. The issue is invalid.
