### ISSUE TITLE
iPad 4 (iOS 10.3.4), Copy Font to Core Folder does not work

### ISSUE THREAD

**Issue by r0my** [PoomSmart/EmojiLibrary#21]
Hello and first, thank you very much for your years of great work. 

I renewed my old ipad 4 with ios 10.3.4, jailbroken with h3lix, for my kids. 

After installing fresh firmware, helix jb, installing filza from dev, I went straight to the manual emoji instructions. 

On all previous iPhones, I never had any problems. But here I can't copy the downloaded font file to the core folder. 

Previously I moved both original files to a backup folder in Documents, then I copied the new downloaded font file to the folder, but after a second the progress window closed and the file is not there. 

I tried several times to restart the iPad, change the permission of the new file and overwrite the old file. Reinstall firmware, jb again. But to no avail. 
However, copying back the old two files works fine. 

Now I am a bit perplexed and ask for help. 

Kind regards 

Romy

Translated with www.DeepL.com/Translator (free version)

**Comment by PoomSmart** [comment]
How many emoji font files in Core folder after you copied the new one to there?

**Comment by r0my** [comment]
Before i copied, there were two emoji foles there. 

AppleColorEmoji@2x.ccf
AppleColorEmoji@2x.ttc

After i edit the file extension from .ccf and .ttc to .BACKUPccf and .BACKUPttc ; let them in the same folder at this time, then i try to copied the new emoji file @2x.ttc with 216,9MB to Core folder but it is not there. No emoji files. 

Same case, wenn i moved the both originals to document for backing up. No new font file in Core folder. 

I'm frustrating.

**Comment by r0my** [comment]
![Uploading 1E4297E1-C54B-4A52-B53D-58F057FDF06B.png…]()

**Comment by r0my** [comment]
![03D97F55-7A72-4A66-A60F-60721025A9ED](https://user-images.githubusercontent.com/12330184/142725473-f7857c93-b62c-40f0-94b6-b3eca6f6cefa.png)

**Comment by PoomSmart** [comment]
With the screenshot you sent, you are right about copying `AppleColorEmoji@2x.ttc` which its size is about 200 MB to here. You have to make sure your system partition has enough free spaces (over 200 MB). You can check the available spaces by scrolling to the bottom of the directory in Filza that you open.

**Comment by PoomSmart** [comment]
Because it looks like the emoji font could not be copied. The only reason I can think of is the lack of free spaces. You can use iCleaner Pro to clean up unused files.

**Comment by r0my** [comment]
You are so wonderful!

Yes, that was it. I never had a look for that. I deleted some languages, wallpapers and some more via icleaner and got over 500mb free now (before 43mb). Copy after that works without problems. Now i have the new emojis on my old ipad and my son is happy about that. 

Here is a screenshot: 

![CFA52986-B1A3-4D49-962E-8AC674D5DEA8](https://user-images.githubusercontent.com/12330184/142729122-b1c64f31-75d8-4c73-b77d-9aef1cff3a2c.jpeg)

Thank you poomsmart again for helping me so brillant. 😘
