### ISSUE TITLE
Emojis can only be viewed and used in some app

### ISSUE THREAD

**Issue by gerbil-snot** [PoomSmart/EmojiLibrary#22]
Hopefully this is just some stupid issue I overlooked, but after following this tutorial: 

https://reddit.com/r/jailbreak/comments/seu6tb/tutorial_emojiport_ios_120148_guide_to_install/

and after checking permissions/file location:

![image](https://user-images.githubusercontent.com/29874563/151633414-3f3d58b2-e235-4fc8-a9ee-6560f50f303e.png)
![image](https://user-images.githubusercontent.com/29874563/151633421-7399185b-f957-4698-a92c-b78442bb83f2.png)

and after respringing, userspace rebooting, and hard reseting (even ran iCleaner) the emojis only appear in some apps. Some of these apps include Apollo, Safari, Github, and Zebra. Apps that it won't show in, like Messages or Messenger, can search for the new ones but only show a question mark box. 

Any suggestions?

**Comment by PoomSmart** [comment]
Your device and OS? Did you see the original emoji font before you replaced it with a new one?

**Comment by gerbil-snot** [comment]
Sorry, forgot to include that

iOS 14.3 iPhone 12 Pro Max

If by original you mean the normal 14.3 emoji then yes, I never had issues seeing those

**Comment by gerbil-snot** [comment]
unc0ver + fugu jailbreak if that matters

**Comment by PoomSmart** [comment]
Do you have EmojiFontManager and other emoji font installed?

**Comment by gerbil-snot** [comment]
I don't have EmojiFontManager, I do have these though:
![image](https://user-images.githubusercontent.com/29874563/151643292-271fd19e-60e1-4d54-a8de-c775cc6c1d05.jpeg)

**Comment by PoomSmart** [comment]
Everything at the latest version?

**Comment by PoomSmart** [comment]
What does it look like on apps that can't show new emojis?

**Comment by gerbil-snot** [comment]
Here's a few screenshots:

![image](https://user-images.githubusercontent.com/29874563/151643611-1e62090b-c7ef-43b4-9273-f675faed4da3.jpeg)
![image](https://user-images.githubusercontent.com/29874563/151643612-92ff6ad1-4573-4104-8de5-18442395c7c0.jpeg)
![image](https://user-images.githubusercontent.com/29874563/151643616-d4dcac74-bfe5-44ef-80a2-301aa65cc522.jpeg)

**Comment by gerbil-snot** [comment]
Sorry to waste your time, just disabled all other tweaks but EmojiPort and it's now working, must be a conflicting tweak. I'll have to narrow it down
