### ISSUE TITLE
Diversity emojis are not showing on iOS 10.1.1 on an iPhone 7

### ISSUE THREAD

**Issue by ibrahimqatar** [PoomSmart/EmojiLibrary#3]
I updated to the latest version and I still can't get them to show. The update fixes the blank keyboard though.

I also used the latest font too (which was updated around an hour ago).

The diversity works fine on my iPhone X on 11.3.1 btw.

**Comment by 2600box** [comment]
Same experience with an ip7 and 10.1.1

**Comment by ibrahimqatar** [comment]
The new update shows the diversity but it has a bug where it always shows the selection menu even though I only tap (without holding) on the emoji.
