### ISSUE TITLE
Unsupported people emoji characters direction-specifying variations

### ISSUE THREAD

**Issue by OwzygZawg** [PoomSmart/EmojiLibrary#32]
iPhone 7 Plus| iOS 15.8.3

This bug occurs when I try to use emoji fonts from iPhone 11+ with iOS 17.4 or higher, the emojis below seem to be invisible. Is EFM compatible with default Apple emoji font file using the latest iOS version?
![B0E5A347-669B-404A-8E07-E5C1B950D783](https://github.com/user-attachments/assets/7777f93c-3254-4d57-89eb-da37da620ef7)
![384819CD-F74F-443F-935C-08F76EC13909](https://github.com/user-attachments/assets/4770e860-025c-41c5-9104-670fa8d9b1eb)
 The other emojis seem to work fine.

**Comment by PoomSmart** [comment]
Try the following:

1. Install `EmojiPort (iOS 12.0-17.3)` tweak
2. Go to Settings > EmojiFontManager and ensure that `AppleColorEmoji` font is selected.

**Comment by OwzygZawg** [comment]
They’re but I’m using AppleColorEmoji@2x.ttc from iPhone 11 with iOS 17.4 just for fun, all emojis are working fine but only these emojis are showing as an invisible character, they aren’t invisible with AppleColorEmoji-HD.ttc though.Is it a problem with the file or EmojiPort?

**Comment by OwzygZawg** [comment]
I realised the same thing happens if I’m using AppleColorEmoji.ttc from MacOS Sequoia 15.0

**Comment by PoomSmart** [comment]
It would be compatible. I tested on iPadOS 15.7.8, all Emoji tweaks installed and the font is selected correctly in EmojiFontManager.

**Comment by PoomSmart** [comment]
Can you reinstall the emoji font - from my repo?

**Comment by OwzygZawg** [comment]
1. Try exporting AppleColorEmoji-160px.ttc from any iPhone with iOS 17.4+
2. Go to Filza —> var/jb/Library/Themes/EmojiFontManager —> Create new folder —> YourFolderName.font and rename the “AppleColorEmoji-160px.ttc” to “AppleColorEmoji@2x.ttc”
3. Open Setting —> EmojiFontManager —> Select it —> Respring

**Comment by PoomSmart** [comment]
I realized what you mean now. Yes, my emoji fonts are rebuilt to include the flipped version of directional emojis such as 🚶 so that older iOS versions understand those emojis (i.e. 🚶‍➡️). iOS 17.4 emoji fonts only include the unflipped version 🚶 and the OS flips them programmatically.

**Comment by PoomSmart** [comment]
So, every tweak works correctly except for the native emoji font that is not backward compatible.

**Comment by OwzygZawg** [comment]
Oh, all right. Have a wonderful day today!

**Comment by OwzygZawg** [comment]
Do you think it would be possible to create a script where people emoji characters direction-specifying variations are flipped without the need to add them to “AppleColorEmoji-160px.ttc” for those who prefer to use the native emoji font? I'm pretty sure this will be Apple's new method for adding flipped emojis in the future. 😕

**Comment by r0my** [comment]
How can i use flipped emojis? I heard from that a while ago. 
I'm on ios 13.6. Tweaks are all installed. Newer emojis are working on my 11 pro max. 
I checked this flipped thing month ago, but i have no flipped emojis here. When i press and hold i can only change the hair and face color. Thats all.

**Comment by OwzygZawg** [comment]
Can you send screenshot?

**Comment by OwzygZawg** [comment]
Anyway, have you tried updating it or something? I mean, tweaks.

**Comment by r0my** [comment]
> Anyway, have you tried updating it or something? I mean, the tweaks.

I have installed: 
Attributes 1.8.0 b2
FontManager 1.3.5
Port 1.5.0 b3
Port Resources (ios10+) 1.6.0

i think thats all

idk the last time i overwrote font file. Maybe last year? 
I can check my emojis and the yearly newcomer, so i know the installed font file. 
 And yes, i can send screenshots. 

![image](https://github.com/user-attachments/assets/461c382c-922a-4dde-9f9f-d20e26823868)


When did the flipped emojis come out?

**Comment by OwzygZawg** [comment]
Oh, apple introduced these new flipped emojis on iOS 17.4 beta 1 and released it to the public with iOS 17.4 official release on March 5, they are actually their unflipped emojj variations and the OS flips them programmatically as @PoomSmart have said.

**Comment by OwzygZawg** [comment]
PoomSmart had to add the new flipped emojis because Apple’s native emoji font doesn’t have their flipped variations.

**Comment by PoomSmart** [comment]
> Do you think it would be possible to create a tweak where people emoji characters direction-specifying variations are flipped without the need to add them to “AppleColorEmoji-160px.ttc” for those who prefer to use the native emoji font? I'm pretty sure this will be Apple's new method for adding flipped emojis in the future. 😕

I thought about it but unable to find the logic that flips the emojis on-the-fly on iOS 17+ yet. Even if I found it, the effort to backport it and ensure it works from like iOS 5 to iOS 16 would be colossal.

**Comment by OwzygZawg** [comment]
So, no luck? I'd love to use the iOS 17.4+ native emoji font. 😪

**Comment by PoomSmart** [comment]
Right now, unlikely. With a much simpler solution in place, it'd rather stick with it.

Also, my fonts are technically smaller and faster. 😁

**Comment by OwzygZawg** [comment]
I'll get used to it

**Comment by OwzygZawg** [comment]
> Right now, unlikely. With a much simpler solution in place, it'd rather stick with it.
> 
> Also, my fonts are technically smaller and faster. 😁

So, do you plan doing it in the future or something? I hope Apple fix it on iOS 18.4+

**Comment by OwzygZawg** [comment]
I’m going to use your font and letting the native one as a placeholder instead.
