### ISSUE TITLE
New emojis under 15.1.1 Dopamine roothide

### ISSUE THREAD

**Issue by r0my** [PoomSmart/EmojiLibrary#33]
Hellooo 🤗🤗🤗

I hope, i'm right here. 

Hi, I have a new iPhone 12 PM with 15.1.1.
Because of my banking apps I have taken Dopamine roothide.
Now I would like to use the nice new emojis again like on my old 11 PM with 13.6 and uncover.

I have installed all the tweaks but the folder with the Apple font is read-only.

Is anyone familiar with roothide and knows how to do this?

![image](https://github.com/user-attachments/assets/ad080151-76f1-4a23-a679-7a4d218ab081)

I'm a bit curious. The only applecoloremoji file on my decice is named: 

AppleColorEmoji-160px.ttc

and it is located at:

/System/Library/Font/CoreAddition (but writeprotect)

On this site here https://github.com/PoomSmart/EmojiFonts/releases
there are a few assets but not with the 160px. 

Edit: ok, when i download the HD version, it downloads the 160px 

Let me try the way with WDBFontOverwrite. 

Ok, this works as long i'm not in jb mode. After i jailbreak with Dopamine roothide, only my old emojis are visible. 
![image](https://github.com/user-attachments/assets/95d154df-a990-4344-8d60-64c8645ceda3)

not the new blue heart at example 

![image](https://github.com/user-attachments/assets/eb5ea31a-2aa0-48cb-ab71-38af4101471c)

my next question is, can i use the emojis which i can see with WDB in trollstoremode in my jb mode? 

When i'm in jb mode, i tried to use WDB and import the new emoji font. apply and respring. Then i got in save mode, exit safe mode, but no new emojis. 

Then i tried the other fonds in WBS line Comic Sans. Same way, with safe Mode but i can see the comic sans font system wide. 

![image](https://github.com/user-attachments/assets/0b70c91d-4c1c-4bb7-b8b2-5c9254d499c3)

so why the emoji font (under emoji font in WDB) is not working? 

hmmm...

**Comment by PoomSmart** [comment]
You need EmojiPort tweak so that new emojis are added to your keyboard. Also an alternative way to install the new emoji font is using EmojiFontManager (EFM) tweak. In my repo, I have emoji fonts that can be downloaded and used with EFM.

**Comment by r0my** [comment]
![image](https://github.com/user-attachments/assets/5ba74c91-5e30-44a7-86fe-aa2f76981cd7)

EmojiFontManager 1.3.5 (from roothide repo) 

No settings
