### ISSUE TITLE
EmojiLibrary v1.0.13+ crashes on iOS 8.4.1

### ISSUE THREAD

**Issue by deepfriedfilth** [PoomSmart/EmojiLibrary#4]
Latest libEmojiLayout.dylib (v1.0.14a/b) is crashing/causing SafeMode also on iPad 2 running iOS 8.4.1 when tapping emoji button on keyboard using iOS 11, 12, or 12.1b2 AppleColorEmoji.ttf. Downgrade EmojiLayout to v1.0.13 and problem persists. Downgrade to v1.0.12 and there is no issue, runs as expected (without new emoji in layout). libEmojiAttributes.dylib version seems irrelevant (tried 1.3.13 + 1.3.14d/e, both work)

Crash log [here](https://pastebin.com/w4rNeMMH). Syslog [here](https://pastebin.com/q43tuyZs).

_Originally posted by @deepfriedfilth in https://github.com/PoomSmart/EmojiLibrary/issues/1#issuecomment-428424772_

**Comment by mkizzle2906** [comment]
the same problem on my 6+ 8.4

**Comment by deepfriedfilth** [comment]
🎉 Working as of v1.0.15.
