### ISSUE TITLE
Emojis are are showing up on pop up view

### ISSUE THREAD

**Issue by KMamedoff** [PoomSmart/EmojiLibrary#6]
![img_9078](https://user-images.githubusercontent.com/5307981/46804103-d5b25480-cd72-11e8-9b3d-1cd80ab2c50f.PNG)

**Comment by maximoney1994** [comment]
having the same issue on here on ios 10.3.3 using the latest font. the three flag issue is still present aswell.

**Comment by maximoney1994** [comment]
worked like a charm.
after reinstalling EmojiPort 1.2.2f the emoji now is displayed correctly when highlighted.
thanks for the tip kind sir.
