### ISSUE TITLE
Emoji Colums & Emoji Darkstyle on 5.1.1

### ISSUE THREAD

**Issue by mkizzle2906** [PoomSmart/EmojiLibrary#8]
Can you fix Emoji columns & Emoji darkstyle face & flag section on ios 5.1.1 ???
![img_0003](https://user-images.githubusercontent.com/32402155/49330948-877a3e80-f5c8-11e8-9791-0338ee9409c5.PNG)

**Comment by BannerBomb** [comment]
I also have a small issue where my keyboard stops scrolling after clicking an emoji that gives an option to select a skin tone and another issue where the keyboard displays question marks and boxes in place of the new emojis. I am using EmojiFontManager and to get the emojis to show again I have to open settings and goto the font manager tweak setting and click Refresh in the top right. I am running iPod Touch 5G iOS 9.3.5 Phoenix jailbreak.

**Comment by PoomSmart** [comment]
This tweak variant will likely be discontinued although the issue has been reported at the wrong place
