### ISSUE TITLE
New 12.1 emojis are not big in Instagram

### ISSUE THREAD

**Issue by mkizzle2906** [PoomSmart/EmojiLibrary#9]
New 12.1 emojis are not big in Instagram
![2f6a1a3e-ea77-43ad-910c-c640d894af04](https://user-images.githubusercontent.com/32402155/49374899-59663d00-f735-11e8-84c5-bb086d5add09.jpeg)

**Comment by PoomSmart** [comment]
IGotAllEmojis tweak fixes this. Instagram defines its own emojis.
